#!/bin/bash

VNC_PORT=$(id -u)0
NOVNC_PORT=$(id -u)1
CODE_SERVER_PORT=$(id -u)2
PASSWORD=$(whoami)pass
VNC_PASSWORD=$PASSWORD
COMPOSE_PROJECT_NAME=centertrack_${USER}

echo "# Auto-generated by ${BASH_SOURCE[0]}" > .env
# COMPOSE_DOCKER_CLI_BUILD=1 delegates docker-compose builds to the docker CLI
# so that docker cache can be used:
# https://github.com/docker/compose/issues/883#issuecomment-555102668
echo "COMPOSE_DOCKER_CLI_BUILD=1" >> .env
# COMPOSE_PROJECT_NAME namespaces docker containers so multiple users can share
# the same computer
echo "COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}" >> .env
# VNC and NOVNC settings
echo "VNC_PORT=${VNC_PORT}" >> .env
echo "NOVNC_PORT=${NOVNC_PORT}" >> .env
echo "PASSWORD=${PASSWORD}" >> .env
echo "VNC_PASSWORD=${VNC_PASSWORD}" >> .env
echo "CODE_SERVER_PORT=${CODE_SERVER_PORT}" >> .env

echo "--------------------------------------"
cat .env
echo "--------------------------------------"
